[profile.default]
build_info = true
extra_output = ["storageLayout"]
solc =  "0.8.20"
evm_version = 'berlin'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
script = 'scripts/foundry'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./"}]

